### PR TITLE
Add macOS support

### PR DESCRIPTION
**Pull request by boomzero**
Without modifying any real code!

### CODE REVIEW

**Comment by boomzero** [comment]
@langningchen

**Comment by boomzero** [comment]
demo:

image

**Comment by boomzero** [comment]
It's actually kind of amazing how you wrote a cross platform app without realizing it.

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
LGTM

**Comment by langningchen** [comment]
@boomzero Thanks for contributing

**Pull request merged**
